TAV:
  - @elastic/elasticsearch
  - apollo-server-express
  - bluebird
  - cassandra-driver
  - elasticsearch
  - express
  - express-graphql
  - express-queue
  - fastify
  - finalhandler
  - generic-pool
  - got
  - graphql
  - handlebars
  - hapi
  - ioredis
  - jade
  - knex
  - koa-router
  - mimic-response
  - mongodb-core
  - mysql
  - mysql2
  - pg
  - pug
  - redis
  - restify
  - tedious
  - ws
